package ui.REPLS;

import ui.EscapeSequences.*;

import static ui.EscapeSequences.*;

public class GameplayUI extends REPL{

    public GameplayUI(){
        String whiteBoard = SET_TEXT_BOLD + SET_TEXT_COLOR_WHITE + SET_BG_COLOR_BLACK + "  White Board:\n\t" + SET_TEXT_COLOR_BLACK +
                SET_BG_COLOR_LIGHT_GREY + "    H  G  F  E  D  C  B  A    " + RESET_BG_COLOR + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 1 " + SET_BG_COLOR_WHITE + BLACK_ROOK + SET_BG_COLOR_LIGHT_GREY + BLACK_KNIGHT + SET_BG_COLOR_WHITE + BLACK_BISHOP + SET_BG_COLOR_LIGHT_GREY + BLACK_KING + SET_BG_COLOR_WHITE + BLACK_QUEEN + SET_BG_COLOR_LIGHT_GREY + BLACK_BISHOP + SET_BG_COLOR_WHITE + BLACK_KNIGHT + SET_BG_COLOR_LIGHT_GREY + BLACK_ROOK + SET_BG_COLOR_LIGHT_GREY + " 1 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 2 " + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + " 2 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 3 " + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 3 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 4 " + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 4 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 5 " + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 5 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 6 " + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 6 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 7 " + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + " 7 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 8 " + SET_BG_COLOR_LIGHT_GREY + WHITE_ROOK + SET_BG_COLOR_WHITE + WHITE_KNIGHT + SET_BG_COLOR_LIGHT_GREY + WHITE_BISHOP + SET_BG_COLOR_WHITE + WHITE_KING + SET_BG_COLOR_LIGHT_GREY + WHITE_QUEEN + SET_BG_COLOR_WHITE + WHITE_BISHOP + SET_BG_COLOR_LIGHT_GREY + WHITE_BISHOP + SET_BG_COLOR_WHITE + WHITE_KNIGHT + SET_BG_COLOR_LIGHT_GREY + WHITE_ROOK + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + "    H  G  F  E  D  C  B  A    " + RESET_BG_COLOR  + "\n\t" + RESET_TEXT_BOLD_FAINT + RESET_TEXT_COLOR;

        String blackBoard = SET_TEXT_BOLD + SET_TEXT_COLOR_WHITE + SET_BG_COLOR_BLACK + "  Black Board:\n\t" + SET_TEXT_COLOR_BLACK +
                SET_BG_COLOR_LIGHT_GREY + "    A  B  C  D  E  F  G  H    " + RESET_BG_COLOR + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 8 " + SET_BG_COLOR_WHITE + WHITE_ROOK + SET_BG_COLOR_LIGHT_GREY + WHITE_KNIGHT + SET_BG_COLOR_WHITE + WHITE_BISHOP + SET_BG_COLOR_LIGHT_GREY + WHITE_QUEEN + SET_BG_COLOR_WHITE + WHITE_KING + SET_BG_COLOR_LIGHT_GREY + WHITE_BISHOP + SET_BG_COLOR_WHITE + WHITE_KNIGHT + SET_BG_COLOR_LIGHT_GREY + WHITE_ROOK + SET_BG_COLOR_LIGHT_GREY + " 8 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 7 " + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + WHITE_PAWN + SET_BG_COLOR_WHITE + WHITE_PAWN + SET_BG_COLOR_LIGHT_GREY + " 7 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 6 " + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 6 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 5 " + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 5 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 4 " + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 4 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 3 " + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + EMPTY + SET_BG_COLOR_WHITE + EMPTY + SET_BG_COLOR_LIGHT_GREY + " 3 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 2 " + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_WHITE + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + BLACK_PAWN + SET_BG_COLOR_LIGHT_GREY + " 2 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + " 1 " + SET_BG_COLOR_LIGHT_GREY + BLACK_ROOK + SET_BG_COLOR_WHITE + BLACK_KNIGHT + SET_BG_COLOR_LIGHT_GREY + BLACK_BISHOP + SET_BG_COLOR_WHITE + BLACK_QUEEN + SET_BG_COLOR_LIGHT_GREY + BLACK_KING + SET_BG_COLOR_WHITE + BLACK_BISHOP + SET_BG_COLOR_LIGHT_GREY + BLACK_KNIGHT + SET_BG_COLOR_WHITE + BLACK_ROOK + SET_BG_COLOR_LIGHT_GREY + " 1 " + RESET_BG_COLOR  + "\n\t" +
                SET_BG_COLOR_LIGHT_GREY + "    A  B  C  D  E  F  G  H    " + RESET_BG_COLOR  + "\n\t" + RESET_TEXT_BOLD_FAINT + RESET_TEXT_COLOR;


        System.out.println(whiteBoard);
        System.out.println();
        System.out.println(blackBoard);
    }

    @Override
    protected Boolean evaluate(String[] parsedInput) {

        switch (parsedInput[0]) {
            case "help":
                System.out.println( SET_TEXT_COLOR_RED + "\thelp" + SET_TEXT_COLOR_LIGHT_GREY + " - List all valid commands" + SET_TEXT_COLOR_RED + "\n\tr" + SET_TEXT_COLOR_LIGHT_GREY + " - Redraws the chess board" + SET_TEXT_COLOR_RED + "\n\tleave" + SET_TEXT_COLOR_LIGHT_GREY + " - Temporarily leaves the game session" + SET_TEXT_COLOR_RED + "\n\tm <STARTING_COLUMN> <STARTING_ROW> - <TARGET_COLUMN> <TARGET_ROW>" + SET_TEXT_COLOR_LIGHT_GREY + " - Moves a piece from the starting location to the target location." +  SET_TEXT_COLOR_RED +"\n\th <SELECTED_PIECE'S_COLUMN> <SELECTED_PIECE'S_ROW>" + SET_TEXT_COLOR_LIGHT_GREY + " - Highlights all available moves for the selected piece"+  SET_TEXT_COLOR_RED +"\n\tresign" + SET_TEXT_COLOR_LIGHT_GREY + " - Forfeits the game");
                break;
            case "quit":
                return true;
//            case "create":
//                break;
//            case "list":
//                break;
//            case "join":
//                break;
            default:
                System.out.println("Ya trash cuz.\ntype help for God's sake");
        }
        return false;
    }

}
